return {
  'nvim-treesitter/nvim-treesitter',
  dependencies = { 'elgiano/nvim-treesitter-angular', branch = 'topic/jsx-fix' },
  opts = {
    ensure_installed = {
      'lua',
      'java',
      -- 'angular',
      'bash',
      'comment',
      'css',
      'dart',
      'dockerfile',
      'git_config',
      'git_rebase',
      'gitattributes',
      'gitcommit',
      'gitignore',
      'graphql',
      'html',
      'http',
      'javascript',
      'jsdoc',
      'json',
      'json5',
      'jsonc',
      'markdown',
      'markdown_inline',
      'mermaid',
      'prisma',
      'python',
      'regex',
      'sql',
      'ssh_config',
      'tmux',
      'tsx',
      'typescript',
      'vue',
      'xml',
      'yaml',
    },
    rainbow = {
      enable = true,
      query = { 'rainbow-parens', html = 'rainbow-tags' },
      extended_mode = true,
      max_file_lines = nil,
    },
    -- nvim-ts-autotag
    autotag = {
      enable_close_on_slash = false,
    },
  },
}
